Merge of expect5-31-branch to mainline

diff --git a/example/kibitz b/example/kibitz
--- a/example/kibitz
+++ b/example/kibitz
@@ -27,10 +27,10 @@ set kibitz "kibitz"		;# where kibitz lives if some unusual place.
 
 # The following code attempts to intuit whether cat buffers by default.
 # The -u flag is required on HPUX (8 and 9) and IBM AIX (3.2) systems.
-if [file exists $exp_exec_library/cat-buffers] {
-	set catflags "-u"
+if {[file exists $exp_exec_library/cat-buffers]} {
+    set catflags "-u"
 } else {
-	set catflags ""
+    set catflags ""
 }
 # If this fails, you can also force it by commenting in one of the following.
 # Or, you can use the -catu flag to the script.
@@ -83,7 +83,7 @@ log_user 0
 set timeout -1
 
 set user [lindex $argv 0]
-if [string match -r $user] {
+if {[string match -r $user]} {
 	send_user "KRUN"	;# this tells user_number 1 that we're running
 				;# and to prepare for possible error messages
 	set user_number 3
@@ -116,7 +116,7 @@ proc is_prefix {do_if0 x xjunk} {
 	if 0!=$do_if0 {return 0}
 	set split [split $xjunk .]
 	for {set i [expr [llength $split]-1]} {$i>=0} {incr i -1} {
-		if [string match $x [join [lrange $split 0 $i] .]] {return 1}
+		if {[string match $x [join [lrange $split 0 $i] .]]} {return 1}
 	}
 	return 0
 }
@@ -124,144 +124,144 @@ proc is_prefix {do_if0 x xjunk} {
 # get domainname.  Unfortunately, on some systems, domainname(1)
 # returns NIS domainname which is not the internet domainname.
 proc domainname {} {
-	# open pops stack upon failure
-	set rc [catch {open /etc/resolv.conf r} file]
-	if {$rc==0} {
-		while {-1!=[gets $file buf]} {
-			if 1==[scan $buf "domain %s" name] {
-				close $file
-				return $name
-			}
-		}
+    # open pops stack upon failure
+    set rc [catch {open /etc/resolv.conf r} file]
+    if {$rc==0} {
+	while {-1!=[gets $file buf]} {
+	    if 1==[scan $buf "domain %s" name] {
 		close $file
+		return $name
+	    }
 	}
+	close $file
+    }
 
-	# fall back to using domainname
-	if {0==[catch {exec domainname} name]} {return $name}
+    # fall back to using domainname
+    if {0==[catch {exec domainname} name]} {return $name}
 
-	error "could not figure out domainname"
+    error "could not figure out domainname"
 }
 
 if $user_number==1 {
-	if $noproc==0 {
-		if [llength $argv]>1 {
-			set pid [eval spawn [lrange $argv 1 end]]
-		} else {
-			# if running as CGI, shell may not be set!
-			set shell /bin/sh
-			catch {set shell $env(SHELL)}
-			set pid [spawn $shell]
-		}
-		set shell $spawn_id
+    if $noproc==0 {
+	if {[llength $argv]>1} {
+	    set pid [eval spawn [lrange $argv 1 end]]
+	} else {
+	    # if running as CGI, shell may not be set!
+	    set shell /bin/sh
+	    catch {set shell $env(SHELL)}
+	    set pid [spawn $shell]
 	}
+	set shell $spawn_id
+    }
 
-	# is user2 remote?
-	regexp (\[^@\]*)@*(.*) $user ignore tmp host
-	set user $tmp
-	if ![string match $host ""] {
-		set h_rc [catch {exec hostname}	hostname]
-		set d_rc [catch domainname 	domainname]
+    # is user2 remote?
+    regexp (\[^@\]*)@*(.*) $user ignore tmp host
+    set user $tmp
+    if ![string match $host ""] {
+	set h_rc [catch {exec hostname}	hostname]
+	set d_rc [catch domainname 	domainname]
 
-		if {![is_prefix $h_rc $host $hostname]
-		 && ![is_prefix $d_rc $host $hostname.$domainname]} {
-			set user2_islocal 0
-		}
+	if {![is_prefix $h_rc $host $hostname]
+	&& ![is_prefix $d_rc $host $hostname.$domainname]} {
+	    set user2_islocal 0
 	}
+    }
 
-	if !$user2_islocal {
-		if $verbose {send_user "connecting to $host\n"}
+    if !$user2_islocal {
+	if $verbose {send_user "connecting to $host\n"}
 
-		if ![info exists proxy] {
-			proc whoami {} {
-				global env
-				if [info exists env(USER)] {return $env(USER)}
-				if [info exists env(LOGNAME)] {return $env(LOGNAME)}
-				if ![catch {exec whoami} user] {return $user}
-				if ![catch {exec logname} user] {return $user}
-				# error "can't figure out who you are!"
-			}
-			set proxy [whoami]
-		}
-		spawn rlogin $host -l $proxy -8
-		set userin $spawn_id
-		set userout $spawn_id
-
-		catch {set prompt $env(EXPECT_PROMPT)}
-
-		set timeout 120
-		expect {
-			assword: {
-				stty -echo
-				send_user "password (for $proxy) on $host: "
-				set old_timeout $timeout; set timeout -1
-				expect_user -re "(.*)\n"
-				send_user "\n"
-				set timeout $old_timeout
-				send "$expect_out(1,string)\r"
-				# bother resetting echo?
-				exp_continue
-			} incorrect* {
-				send_user "invalid password or account\n"
-				exit
-			} "TERM = *) " {
-				send "\r"
-				exp_continue
-			} timeout {
-				send_user "connection to $host timed out\n"
-				exit
-			} eof {
-				send_user "connection to host failed: $expect_out(buffer)"
-				exit
-			} -re $prompt
-		}
-		if $verbose {send_user "starting kibitz on $host\n"}
-		# the kill protects user1 from receiving user3's
-		# prompt if user2 exits via expect's exit.
-		send "$kibitz $kibitz_flags -r $user;kill -9 $$\r"
-
-		expect {
-			-re "kibitz $kibitz_flags -r $user.*KRUN" {}
-			-re "kibitz $kibitz_flags -r $user.*(kibitz\[^\r\]*)\r" {
-				send_user "unable to start kibitz on $host: \"$expect_out(1,string)\"\n"
-				send_user "try rlogin by hand followed by \"kibitz $user\"\n"
-				exit
-			}
-			timeout {
-				send_user "unable to start kibitz on $host: "
-				set expect_out(buffer) "timed out"
-				set timeout 0; expect -re .+
-				send_user $expect_out(buffer)
-				exit
-			}
-		}
-		expect {
-			-re ".*\n" {
-				# pass back diagnostics
-				# should really strip out extra cr
-				send_user $expect_out(buffer)
-				exp_continue
-			}
-			KABORT exit
-			default exit
-			KDATA
-		}
+	if ![info exists proxy] {
+	    proc whoami {} {
+		global env
+		if {[info exists env(USER)]} {return $env(USER)}
+		if {[info exists env(LOGNAME)]} {return $env(LOGNAME)}
+		if {![catch {exec whoami} user]} {return $user}
+		if {![catch {exec logname} user]} {return $user}
+		# error "can't figure out who you are!"
+	    }
+	    set proxy [whoami]
 	}
+	spawn rlogin $host -l $proxy -8
+	set userin $spawn_id
+	set userout $spawn_id
+
+	catch {set prompt $env(EXPECT_PROMPT)}
+
+	set timeout 120
+	expect {
+	    assword: {
+		stty -echo
+		send_user "password (for $proxy) on $host: "
+		set old_timeout $timeout; set timeout -1
+		expect_user -re "(.*)\n"
+		send_user "\n"
+		set timeout $old_timeout
+		send "$expect_out(1,string)\r"
+		# bother resetting echo?
+		exp_continue
+	    } incorrect* {
+		send_user "invalid password or account\n"
+		exit
+	    } "TERM = *) " {
+		send "\r"
+		exp_continue
+	    } timeout {
+		send_user "connection to $host timed out\n"
+		exit
+	    } eof {
+		send_user "connection to host failed: $expect_out(buffer)"
+		exit
+	    } -re $prompt
+	}
+	if {$verbose} {send_user "starting kibitz on $host\n"}
+	# the kill protects user1 from receiving user3's
+	# prompt if user2 exits via expect's exit.
+	send "$kibitz $kibitz_flags -r $user;kill -9 $$\r"
+
+	expect {
+	    -re "kibitz $kibitz_flags -r $user.*KRUN" {}
+	    -re "kibitz $kibitz_flags -r $user.*(kibitz\[^\r\]*)\r" {
+		send_user "unable to start kibitz on $host: \"$expect_out(1,string)\"\n"
+		send_user "try rlogin by hand followed by \"kibitz $user\"\n"
+		exit
+	    }
+	    timeout {
+		send_user "unable to start kibitz on $host: "
+		set expect_out(buffer) "timed out"
+		set timeout 0; expect -re .+
+		send_user $expect_out(buffer)
+		exit
+	    }
+	}
+	expect {
+	    -re ".*\n" {
+		# pass back diagnostics
+		# should really strip out extra cr
+		send_user $expect_out(buffer)
+		exp_continue
+	    }
+	    KABORT exit
+	    default exit
+	    KDATA
+	}
+    }
 }
 
-if $user_number==2 {
-	set pid [string trimleft $user -]
+if {$user_number==2} {
+    set pid [string trimleft $user -]
 }
 
 set local_io [expr ($user_number==3)||$user2_islocal]
-if $local_io||($user_number==2) {
-	if 0==[info exists pid] {set pid [pid]}
+if {$local_io||($user_number==2)} {
+    if {0==[info exists pid]} {set pid [pid]}
 
-	set userinfile /tmp/exp0.$pid
-	set useroutfile /tmp/exp1.$pid
+    set userinfile /tmp/exp0.$pid
+    set useroutfile /tmp/exp1.$pid
 }
 
 proc prompt1 {} {
-	return "kibitz[info level].[history nextid]> "
+    return "kibitz[info level].[history nextid]> "
 }
 
 set esc_match {}
@@ -278,54 +278,52 @@ if {$allow_escape} {
 }
 
 proc prompt1 {} {
-	return "kibitz[info level].[history nextid]> "
+    return "kibitz[info level].[history nextid]> "
 }
 
 set timeout -1
 
 # kibitzer executes following code
-if $user_number==2 {
-	# for readability, swap variables
-	set tmp $userinfile
-	set userinfile $useroutfile
-	set useroutfile $tmp
+if {$user_number==2} {
+    # for readability, swap variables
+    set tmp $userinfile
+    set userinfile $useroutfile
+    set useroutfile $tmp
 
-	if ![file readable $userinfile] {
-		send_user "Eh?  No one is asking you to kibitz.\n"
-		exit -1
-	}
- 	spawn -open [open "|cat $catflags < $userinfile" "r"]
-	set userin $spawn_id
+    if ![file readable $userinfile] {
+	send_user "Eh?  No one is asking you to kibitz.\n"
+	exit -1
+    }
+    spawn -open [open "|cat $catflags < $userinfile" "r"]
+    set userin $spawn_id
 
-	spawn -open [open $useroutfile w]
-	set userout $spawn_id
-	# open will hang until other user's cat starts
+    spawn -open [open $useroutfile w]
+    set userout $spawn_id
+    # open will hang until other user's cat starts
 
-	stty -echo raw
-	if $allow_escape {send_user "Escape sequence is $escape_printable\r\n"}
+    stty -echo raw
+    if {$allow_escape} {send_user "Escape sequence is $escape_printable\r\n"}
 
-	# While user is reading message, try to delete other fifo
-	catch {exec rm -f $userinfile}
+    # While user is reading message, try to delete other fifo
+    catch {exec rm -f $userinfile}
 
-	eval interact $esc_match \
-		-output $userout \
-		-input $userin
+    eval interact $esc_match \
+	    -output $userout \
+	    -input $userin
 
-	exit
+    exit
 }
 
 # only user_numbers 1 and 3 execute remaining code
 
 proc abort {} {
-	global user_number
-
-	# KABORT tells user_number 1 that user_number 3 has run into problems
-	# and is exiting, and diagnostics have been returned already
-	if $user_number==3 {send_user KABORT}
-	exit
+    # KABORT tells user_number 1 that user_number 3 has run into problems
+    # and is exiting, and diagnostics have been returned already
+    if {$::user_number==3} {send_user KABORT}
+    exit
 }
 
-if $local_io {
+if {$local_io} {
     proc mkfifo {f} {
 	if 0==[catch {exec mkfifo $f}] return		;# POSIX
 	if 0==[catch {exec mknod $f p}] return
@@ -349,7 +347,7 @@ if $local_io {
     # make sure other user can access despite umask
     exec chmod 666 $userinfile $useroutfile
 
-    if $verbose {send_user "asking $user to type:  kibitz -$pid\n"}
+    if {$verbose} {send_user "asking $user to type:  kibitz -$pid\n"}
 
     # can't use exec since write insists on being run from a tty!
     set rc [catch {
@@ -357,7 +355,7 @@ if $local_io {
 			/bin/write $user $tty
 		}
 	]
-    if $rc {rmfifos;abort}
+    if {$rc} {rmfifos;abort}
 
     spawn -open [open $useroutfile w]
     set userout $spawn_id
@@ -370,37 +368,41 @@ if $local_io {
 
 stty -echo raw
 
-if $user_number==3 {
-	send_user "KDATA"	;# this tells user_number 1 to send data
+if {$user_number==3} {
+    send_user "KDATA"	;# this tells user_number 1 to send data
 
-	interact {
-		-output $userout
-		-input $userin eof {
-			wait -i $userin
-			return -tcl
-		} -output $user_spawn_id 
-	}
+    interact {
+	-output $userout
+	-input $userin eof {
+	    wait -i $userin
+	    return -tcl
+	} -output $user_spawn_id 
+    }
 } else {
-	if $allow_escape {send_user "Escape sequence is $escape_printable\r\n"}
+    if {$allow_escape} {send_user "Escape sequence is $escape_printable\r\n"}
 
-	if $noproc {
-		interact {
-			-output $userout
-			-input $userin eof {wait -i $userin; return}
-			-output $user_spawn_id
-		}
-	} else {
-		eval interact $esc_match {
-			-output $shell \
-			-input $userin eof {
-				wait -i $userin
-				close -i $shell
-				return
-			} -output $shell \
-			-input $shell -output "$user_spawn_id $userout"
-		}
-		wait -i $shell
+    if {$noproc} {
+	interact {
+	    -output $userout
+	    -input $userin eof {wait -i $userin; return}
+	    -output $user_spawn_id
 	}
+    } else {
+	eval interact $esc_match {
+	    -output $shell \
+		    -input $userin eof {
+		wait -i $userin
+		close -i $shell
+		return
+	    } -output $shell \
+		    -input $shell eof {
+		close -i $userout
+		wait -i $userout
+		return
+	    } -output "$user_spawn_id $userout"
+	}
+	wait -i $shell
+    }
 }
 
-if $local_io rmfifos
+if {$local_io} rmfifos
